# Site settings
title: egnitessam
email: egnitessam@gmail.com

description: > # this means to ignore newlines until "baseurl:"
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. 

baseurl: "" # the subpath of your site, e.g. /blog/

# url: "http://egnitessam.ddns.net" # the base hostname & protocol for your site

twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Instruct Jekyll to load Bootstrap
sass:

sass_dir: _sass