# Site settings
title: egnitessam
email: egnitessam@gmail.com

description: > # this means to ignore newlines until "baseurl:"
		Atelier Kredewahn (Pausa), Produktdesign Popp (Beka), Portrait- und Aktkurse bei Bildhauerin Charlotte Traum, Studienaufenthalt Atelier Langlet(Seguret, Provence), Specksteine, Sozialstudien Stuttgart, Indienreise, Norwegenreise
baseurl: "" # the subpath of your site, e.g. /blog/

# url: "http://egnitessam.ddns.net" # the base hostname & protocol for your site

twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Instruct Jekyll to load Bootstrap
sass:

sass_dir: _sass